#   AutoVersion for Xcode, for Swift
#   Copyright 2015 Malcolm Teas.  See https://github.com/malcolmteas/AutoVersionXcode

#   This uses the Version (CFBundleShortVersionString), Build (CFBundleVersion), and Bundle
#   Identifier fields in your project's General tab (also in the Info.plist file).

#   The copyright info comes from a Copyright.xcconfig file that's added into the
#   project's configurations.  The COPYRIGHT_NAME and COPYRIGHT_YEAR values could be added in
#   any other config file.  Alternately, you could add a user-defined build setting too.

#   The version is a three digit version like 1.2.3 as in http://semver.org followed by d for
#   development, a for alpha, or b for beta.  Release has no letter.  When you submit to the
#   app store it will need to be as a release, no trailing letters and in Release
#   configuration. Multiple betas, for example, can be done as 1.2.3b3 for beta 3.  This works
#   for development or alpha versions if you use those.  Development means "not at all feature
#   complete". Alpha is "mostly feature complete".  Beta is "feature complete, but buggy".
#   Some groups use a "Final" which is for testing just pre-release.  Using development,
#   alpha, beta, or final is completely optional.

#   All values are created in version.swift to be used at runtime.  Some data is printed
#   in the build log for reference as well.

#   Get the version, and extract the parts of it.  Relies on version format as above.
version=`/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "${INFOPLIST_FILE}" `
phaseLetter=${version//[^a-z]/}
phaseLetter=`echo $phaseLetter | tr "[:lower:]" "[:upper:]"`
phaseNumber=${version##*[a-z]}
simpleVersion=${version%%[a-z]*}

#   Get the git commit hash short version so we can track builds in the repo
buildHash=`git rev-parse --short=5  HEAD | tr "[:lower:]" "[:upper:]"`
if ! git diff --quiet
then
    buildHash="${buildHash}-dirty"      # Has un-committed changes.
fi

#   The build number needs to increment for each app store submission. Here it's
#   automatically updated for each release build, in hex format for compactness.
buildNumber=`/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "${INFOPLIST_FILE}" `
if [ "$CONFIGURATION" = "Release" ]
then
    buildNumber=$(($buildNumber + 1))
    buildNumber=$(printf "%X" $buildNumber)
    /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $buildNumber" "${INFOPLIST_FILE}"
fi
buildCode="${buildNumber}-${buildHash}"

#   Put it all together
fullversion="${version}-${buildCode}"

#   Get app id
appID=`/usr/libexec/PlistBuddy -c "Print :CFBundleIdentifier" "${INFOPLIST_FILE}" `

#  Write out the version to the console
echo "${PRODUCT_NAME} ${fullversion} built in ${CONFIGURATION} configuration"
echo "Build with ${SDK_NAME} with Xcode ${XCODE_VERSION_ACTUAL}. (See version.h.)"

#  Write out the version.swift file
echo "//  Application version information automatically generated at build time." > version.swift
echo "//  Do not commit this file to your code repository." >> version.swift
echo "//  This is generated by a script in Run Script build phase." >> version.swift
echo "//  See script for details on updating version and copyright." >> version.swift

echo >> version.swift
echo "//  Application information" >> version.swift
echo "let ApplicationName = \"${PRODUCT_NAME}\"" >> version.swift
echo "let Configuration = \"${CONFIGURATION}\"    // Configuration: Debug, Release, etc" >> version.swift
echo "let CopyrightName = \"${COPYRIGHT_NAME}\"" >> version.swift
echo "let CopyrightYear = \"${COPYRIGHT_YEAR}\"" >> version.swift
echo "let Copyright = \"Copyright ${COPYRIGHT_YEAR} by ${COPYRIGHT_NAME}. All rights reserved.\"" >> version.swift

echo >> version.swift
echo "//  Version information" >> version.swift
echo "let FullVersion = \"${fullversion}\"" >> version.swift
echo "let Version = \"${version}\"    // From Summary tab or short bundle string in plist file" >> version.swift
echo "let SimpleVersion = \"${simpleVersion}\"" >> version.swift

echo >> version.swift
echo "//  Information about this build" >> version.swift
echo "let BuildNumber = \"${buildNumber}\"    // Increment this by changing CFBundleVersion in app plist." >> version.swift
echo "let BuildHash = \"${buildHash}\"        // git commit hash (dirty if not checked in)" >> version.swift
echo "let BuildCode = \"${buildCode}\"" >> version.swift

echo >> version.swift
echo "//  Environment version" >> version.swift
echo "let XCODE_VERSION = \"${XCODE_VERSION_ACTUAL}\"" >> version.swift
echo "let SDK_NAME = \"${SDK_NAME}\"" >> version.swift
echo "let DEPLOYMENT_TARGET = \"${IPHONEOS_DEPLOYMENT_TARGET}\"" >> version.swift

echo >> version.swift
echo "//  Release phase" >> version.swift
echo " enum ReleasePhaseEnum {" >> version.swift
echo "    case Dev, Alpha, Beta, Final, Release" >> version.swift
echo " }" >> version.swift
echo >> version.swift

if [[ "$phaseLetter" == "D" ]]
then
    echo "var ReleasePhase: ReleasePhaseEnum = .Dev" >> version.swift
    echo "let PhaseNumber = ${phaseNumber}" >> version.swift
fi
if [[ "$phaseLetter" == "A" ]]
then
    echo "var ReleasePhase: ReleasePhaseEnum = .Alpha" >> version.swift
    echo "let PhaseNumber = ${phaseNumber}" >> version.swift
fi
if [[ "$phaseLetter" == "B" ]]
then
    echo "var ReleasePhase: ReleasePhaseEnum = .Beta" >> version.swift
    echo "let PhaseNumber = ${phaseNumber}" >> version.swift
fi
if [[ "$phaseLetter" == "F" ]]
then
    echo "var ReleasePhase: ReleasePhaseEnum = .Final" >> version.swift
    echo "let PhaseNumber = ${phaseNumber}" >> version.swift
fi
if  [[ "$phaseLetter" == "" ]]
then
    echo "var ReleasePhase: ReleasePhaseEnum = .Release" >> version.swift
    echo "let PhaseNumber = 0" >> version.swift
fi
